version: '1'
services:
  notebook:
    build: .
    ports:
      - "8888:8888"  # Mapeando a porta 8888 do contêiner para a porta 8888 do host
    volumes:
      - .:/home/jovyan/work  # Mapeando a pasta local para a pasta no contêiner
    environment:
      - JUPYTER_ENABLE_LAB=yes  # Habilitar o Jupyter notebook
    command: start-notebook.sh --ip=0.0.0.0 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*'

 